name: config-program
dependencies:
- base
- rio

# configuration
- etc
- file-embed
- aeson

# database
- persistent-postgresql
- persistent-template
- resource-pool
executables:
  config-program:
    source-dirs: app
    main: Main.hs
