name: config-program
dependencies:
- base
- rio
- rio-orphans

# configuration
- etc
- file-embed
- aeson

# database
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- resource-pool

executables:
  config-program:
    source-dirs: app
    main: Main.hs
