etc/files:
  env: APP_CONFIG_FILE
  paths:
  - ./config/development.yaml
  - /etc/my-app/integration.yaml
  - /etc/my-app/production.yaml

etc/entries:
  logging:
    verbose:
      default: False
      env: APP_LOG_VERBOSE
    handle:
      default: 'stdout'
      env: APP_LOG_HANDLE

  database:
    username:
      etc/spec:
        default: lc2018
        type: string
        env: APP_DB_USER
        cli:
          long: user
          meta: USERNAME
    password:
      etc/spec:
        type: string
        sensitive: true
        env: APP_DB_PASSWORD
        cli:
          long: user
          meta: USERNAME
